### ISSUE TITLE
Multiline docstrings are not handled well - do not propagate to documentation

### ISSUE THREAD

**Issue by pgleeson** [ModECI/modelspec#13]
e.g. this:
https://github.com/ModECI/modelspec/blob/0cdcac0f2bd4f139846c6b5ab18518d945ee4cef/examples/document.py#L22-L26

is only the last line in generated docs:

https://github.com/ModECI/modelspec/blob/0cdcac0f2bd4f139846c6b5ab18518d945ee4cef/examples/document.specification.json#L26

Required for proper documentation of MDF...

**Comment by pgleeson** [comment]
Something for @parikshit14 to look into.

**Comment by davidt0x** [comment]
Hey @parikshit14,

Can you check if it parses the first line into the short_description attribute without modifying the docstring? If so, then I would just concatenate the short and long description if they are both present. I would rather not change the docstring formatting if possible since it is a standard.

**Comment by pgleeson** [comment]
Fixed by #14
